### PR TITLE
Minor - Parser should also recognize MathML-Presentation annotation #27

### PR DESCRIPTION
**Pull request by vstange**
Is the change okay?

### CODE REVIEW

**Comment by vstange** [comment]
@AndreG-P could you review and merge this?

**Comment by physikerwelt** [comment]
a test would be good. otherwise it's hard to understand the change

**Comment by vstange** [comment]
Okay, I added a test case and skipped the render test ... a mistake. Seems like mathoid svg rendering can't handle formulas like 
```
<math xmlns="http://www.w3.org/1998/Math/MathML" id="p1.1.m1.1" class="ltx_Math" alttext="m" display="inline">
  <semantics id="p1.1.m1.1a">
    <ci id="p1.1.m1.1.1.cmml" xref="p1.1.m1.1.1">𝑚</ci>
    <annotation-xml encoding="MathML-Presentation" id="p1.1.m1.1b">
	<mi id="p1.1.m1.1.1" xref="p1.1.m1.1.1.cmml">m</mi>
    </annotation-xml>
  </semantics>
</math>
```
I will try to take a look tomorrow.

**Comment by AndreG-P** [comment]
It's maybe because there is no apply tag in the content MML subtree. Sounds strange but we already faced this issue a couple of times.

**Comment by physikerwelt** [comment]
Now the pull request looks good in theory. The change is small and well tested. So now only the logic must be fixed.

**Comment by physikerwelt** [comment]
mathoid is a rendering engine for presentation mathml. rendering content mathml is not in the scope.

**Comment by vstange** [comment]
can't be fixed at the moment, see https://github.com/ag-gipp/vmext/issues/27

**Comment by vstange** [comment]
reviewed your changes: ok

**Pull request merged**
